name: Build 3secOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install NASM
      run: sudo apt-get install nasm

    - name: Build OS
      run: make

    - name: Upload bootable image
      uses: actions/upload-artifact@v4
      with:
        name: bootable-image
        path: bootable.img
